# Generated by Django 4.1.5 on 2023-02-08 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirect',
            old_name='e',
            new_name='author',
        ),
    ]
