# Generated by Django 4.1.5 on 2023-02-10 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0002_rename_e_redirect_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='fonts',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='data',
            name='ip',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='data',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redirect',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='language',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='data',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='data',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
