# Generated by Django 4.1.5 on 2023-02-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirect', '0003_data_fonts_data_ip_data_time_redirect_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='redirect',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='redirect.redirect'),
            preserve_default=False,
        ),
    ]
