# Generated by Django 4.1.5 on 2023-01-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_bids_bid_rename_comments_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listings_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
